# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/todo',
                'doc_host': 'https://Deufel.github.io',
                'git_url': 'https://github.com/Deufel/todo',
                'lib_path': 'todo'},
  'syms': {'todo.core': {'todo.core.foo': ('core.html#foo', 'todo/core.py')}}}
