"""The main FastHTML application for the contacts app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_app.ipynb.

# %% auto 0
__all__ = ['create_app']

# %% ../nbs/05_app.ipynb 2
from fasthtml.common import *
from .core import *
from .auth import *
from .routes import *

# %% ../nbs/05_app.ipynb 3
def create_app():
    "Create and configure the FastHTML application"
    # Create beforeware
    bware = Beforeware(before, skip=[r'/favicon\.ico', r'/static/.*', r'.*\.css', '/login'])
    
    # Create app with configuration
    app = FastHTML(
        before=bware,
        exception_handlers={404: _not_found},
        hdrs=(
            picolink,
            Style(':root { --pico-font-size: 100%; }'),
            SortableJS('.sortable'),
            Script(markdown_js, type='module')
        )
    )
    
    # Add routes
    rt = app.route
    
    # Static file handler
    @rt("/{fname:path}.{ext:static}")
    def get(fname:str, ext:str): 
        return FileResponse(f'{fname}.{ext}')
    
    # Add all route groups
    login_routes(rt)
    todo_routes(rt)
    
    return app


