"""The main FastHTML application for the contacts app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_app.ipynb.

# %% auto 0
__all__ = ['create_app', 'run_app']

# %% ../nbs/05_app.ipynb 4
def create_app(db=default_db):
    "Create and configure the FastHTML application"
    app, rt = fast_app(
        hdrs=(
            Style("""
                body { 
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 1200px;
                    margin: 0 auto;
                    padding: 0 1rem;
                }
                button {
                    background-color: #4CAF50;
                    color: white;
                    border: none;
                    padding: 8px 16px;
                    margin-right: 8px;
                    border-radius: 4px;
                    cursor: pointer;
                }
                button:hover {
                    background-color: #45a049;
                }
            """),
        ),
        static_path="static"
    )
    
    # Add the Vary header for proper caching
    @app.middleware("http")
    async def add_vary_header(request, call_next):
        "Add Vary header to responses for proper caching with HTMX"
        response = await call_next(request)
        response.headers["Vary"] = "HX-Request"
        return response
    
    # Set up all routes
    setup_routes(app, rt, db)
    
    return app, rt

# %% ../nbs/05_app.ipynb 6
def run_app(host="0.0.0.0", port=5001, db=default_db):
    "Create and run the contacts application"
    app, _ = create_app(db)
    
    import uvicorn
    uvicorn.run(app, host=host, port=port)

# %% ../nbs/05_app.ipynb 8
if __name__ == "__main__":
    run_app()
