"""Reusable ui components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_components.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_components.ipynb 4
# Todo component rendering
@patch
def __ft__(self:Todo):
    "Render a Todo item as an FT component"
    show = AX(self.title, f'/todos/{self.id}', 'current-todo')
    edit = AX('edit', f'/edit/{self.id}', 'current-todo')
    dt = '✅ ' if self.done else ''
    cts = (dt, show, ' | ', edit, Hidden(id="id", value=self.id), Hidden(id="priority", value="0"))
    return Li(*cts, id=f'todo-{self.id}')
