"""Core utilities and imports for the contacts application"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_core.ipynb 4
from fasthtml.common import *
from fastcore.test import *
