"""Core utilities and imports for the contacts application"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['markdown_js', 'clr_details']

# %% ../nbs/00_core.ipynb 4
from fasthtml.common import *
from hmac import compare_digest

# %% ../nbs/00_core.ipynb 5
# Utility functions
def clr_details(): 
    "Create a div to clear details view with out-of-band swap"
    return Div(hx_swap_oob='innerHTML', id='current-todo')

# %% ../nbs/00_core.ipynb 6
# JavaScript for markdown parsing
markdown_js = """
import { marked } from "https://cdn.jsdelivr.net/npm/marked/lib/marked.esm.js";
proc_htmx('.markdown', e => e.innerHTML = marked.parse(e.textContent));
"""

# %% ../nbs/00_core.ipynb 7
# Error handlers
def _not_found(req, exc): 
    "404 error handler"
    return Titled('Oh no!', Div('We could not find that page :('))
