"""Datamodels"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_db.ipynb.

# %% auto 0
__all__ = ['db', 'todos', 'users', 'Todo', 'User', 'init_db', 'Login']

# %% ../nbs/01_db.ipynb 3
from fasthtml.common import *
from dataclasses import dataclass

# %% ../nbs/01_db.ipynb 4
# Database setup
db = database('data/utodos.db')
todos, users = db.t.todos, db.t.users

# %% ../nbs/01_db.ipynb 5
# Initialize database if needed
def init_db():
    "Initialize database tables if they don't exist"
    if todos not in db.t:
        users.create(dict(name=str, pwd=str), pk='name')
        todos.create(id=int, title=str, done=bool, name=str, details=str, priority=int, pk='id')
    return todos.dataclass(), users.dataclass()

# %% ../nbs/01_db.ipynb 6
# Create dataclasses for our models
Todo, User = init_db()

# %% ../nbs/01_db.ipynb 7
@dataclass
class Login: 
    "Login form data class"
    name: str
    pwd: str
