"""builds the main.py file from other modules"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_app.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'add_vary_header']

# %% ../nbs/05_app.ipynb 3
from fasthtml.common import *
#from routes import setup_routes

# %% ../nbs/05_app.ipynb 4
app, rt = fast_app(
    hdrs=(
        Style()# TODO add Style Link HERE... need to make styles in set up module..),
    ),
    static_path="static"
)

# %% ../nbs/05_app.ipynb 5
# Add the Vary header for proper caching
@app.middleware("http")
async def add_vary_header(request, call_next):
    response = await call_next(request)
    response.headers["Vary"] = "HX-Request"
    return response

# Set up all routes
setup_routes(app, rt)

if __name__ == "__main__":
    serve()
