"""Datamodels"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_models.ipynb.

# %% auto 0
__all__ = ['Contact']

# %% ../nbs/01_models.ipynb 4
from dataclasses import dataclass
from fastcore.basics import *

# %% ../nbs/01_models.ipynb 6
@dataclass
class Contact:
    "Represents a contact in our address book"
    id: int        # Unique identifier
    name: str      # Full name
    email: str     # Email address
    phone: str     # Phone number
    address: str   # Physical address
    favorite: bool = False  # Whether this is a favorite contact

# %% ../nbs/01_models.ipynb 12
@patch
def _repr_markdown_(self:Contact):
    "Rich display for Contact objects in notebooks"
    star = "⭐" if self.favorite else ""
    return f"""
    ### {self.name} {star}
    
    - **Email:** {self.email}
    - **Phone:** {self.phone}
    - **Address:** {self.address}
    - **ID:** {self.id}
    """
